name: "Update"
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '*/60 * * * *'
jobs:
  update:
    timeout-minutes: 15
    runs-on: nscloud-ubuntu-22.04-amd64-4x16
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # flakes doesn't work on shallow clones
    - name: install-nix
      uses: cachix/install-nix-action@v23
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        extra_nix_config: |
          system-features = kvm nixos-test
    - uses: cachix/cachix-action@v12
      with:
        name: nixpkgs-wayland
        signingKey: '${{ secrets.cachix_key_nixpkgs_wayland }}'
    - name: git-setup
      run: |
        git config --global user.name 'Cole Botkens'
        git config --global user.email 'cole.mickens+colebot@gmail.com'
    - name: update
      env:
        CACHIX_SIGNING_KEY: "${{ secrets.cachix_key_nixpkgs_wayland }}"
      run: |
        set -xeuo pipefail
        nix develop -c nix flake update --commit-lock-file
        nix develop -c ./update.sh
    - name: push
      run: |
        git push origin HEAD
